name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 3.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    

  # Common packages
  nb_utils: ^4.6.25
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0

  # Media
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6
  file_picker: ^4.6.1
  just_audio: ^0.9.30
  syncfusion_flutter_pdfviewer: ^20.4.38
  photo_view: ^0.14.0
  appinio_video_player: ^1.2.0
  giphy_get: ^3.2.0

  # APIs
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0

  flutter_html: ^2.2.1
  google_mobile_ads: ^1.3.0

  # State Management Technique
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

  # Share
  share_plus: ^4.0.10
  flutter_custom_tabs: ^1.0.4

  # Firebase
  firebase_crashlytics: ^3.0.1
  firebase_core: 2.1.0
  firebase_auth: 4.0.1
  firebase_messaging: 14.0.1


  # AUTHENTICATION
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1

  # Remote Notification
  onesignal_flutter: 3.4.1

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.1

  lottie: ^1.4.3



  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_launcher_icons: "^0.11.0"
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/


